/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibGuiReusables;

import java.awt.BorderLayout;
import java.util.ArrayList;

/**
 *
 * @author Javi
 */
public abstract class LibFormularioExtensible extends LibFormulario {

    public enum TipoContenedor {
        SIMPLE, PORFICHAS, ARBOL
    }

    private String nombreContenedor;

    private ArrayList<LibFormularioExtensible> hijosExtensibles = new ArrayList<>();

    public void setnombreContenedor(String nombre) {
        nombreContenedor = nombre;
    }

    public String getnombreContenedor() {
        return nombreContenedor;
    }

    public Boolean configurarFormulario() {
        initComponents();
        return true;
    }

    public void addHijoExtensible(LibFormularioExtensible hijo, String titulo) {
        if (!(titulo.isEmpty())) {
            nombreContenedor = titulo;
        }
        hijosExtensibles.add(hijo);
        combinarGui(hijo);

    }

    public void addListaHijosExtensibles(ArrayList<LibFormularioExtensible> listaHijos, String titulo) {
        if (!(titulo.isEmpty())) {
            nombreContenedor = titulo;
        }

        for (LibFormularioExtensible hijo : listaHijos) {
            hijosExtensibles.add(hijo);
            combinarGui(hijo);
        }

    }

    private void combinarGui(LibFormularioExtensible hijo) {

        if (this instanceof LibFormularioSimple) {

            LibFormularioSimple padreSimple = (LibFormularioSimple) this;
            padreSimple.setTitle(nombreContenedor);

            LibFormularioSimple hijoSimple = (LibFormularioSimple) hijo;
            padreSimple.getContentPane().add(hijo.getContentPane());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
