/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibGuiReusables;

import java.awt.event.ActionEvent;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Javi
 */
public class LibFormularioPorFichas extends LibFormularioExtensible  {

    /**
     *
     */
    public LibFormularioPorFichas() {
        initComponents();
    }

    @Override
    public Boolean configurarFormulario() {

        if (super.configurarFormulario()) {

            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void aceptar() {
        System.out.println("has pulsado aceptar");
    }

    @Override
    public void cancelar() {
        System.out.println("has pulsado rechazar");
    }

    @Override
    public void cambiarValor(String nombreComponente, Object valor) {
        System.out.println("cambiar valor");
    }

    @Override
    public void recuperarValorExterno(String nombreComponente, Object valor) {
        System.out.println("recuperar valor");
    }

    @Override
    public void actionPerformed(ActionEvent e) {
         System.out.println("evento Accion");
    }
    
     @Override
    public void stateChanged(ChangeEvent evt) {
         System.out.println("valor cambiado: " + evt.getSource());
    }
}
