package LibGuiReusables;

/**
 * Panel Botones Acpetar y Cancelar
 *
 * @author Javi
 */
public class PanelBotonesEventos extends javax.swing.JPanel {

    // lista de observadores de eventos
    private  GestorEventos gestorEventosPanelBotones;

    /**
     * crear un nuevo PanelBotones y la lista de Observadores de eventos
     */
    public PanelBotonesEventos() {
        initComponents();
        gestorEventosPanelBotones = new GestorEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setMinimumSize(new java.awt.Dimension(460, 40));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(460, 40));
        setLayout(new java.awt.GridLayout(1, 0));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        add(botonAceptar);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        add(botonCancelar);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        EventoPulsarBoton evtPB = new EventoPulsarBoton(evt.getSource());
        lanzarEventoPulsarBoton(evtPB);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        EventoPulsarBoton evtPB = new EventoPulsarBoton(evt.getSource());
        lanzarEventoPulsarBoton(evtPB);
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    // End of variables declaration//GEN-END:variables

    /**
     * notifica el evento a los observadores de la lista
     *
     * @param ActionEvent
     */
    private void lanzarEventoPulsarBoton(EventoPulsarBoton evt) {
        gestorEventosPanelBotones.notificarEvento("PulsarBoton",evt);

    }

    /**
     * incluye un nuevo observador en la lista
     *
     * @param obs onservador
     */
    public void addObservador(Observador obs) {
        gestorEventosPanelBotones.addObservador("PulsarBoton",obs);
    }

}
